import type { MetadataRoute } from "next";
import { getBaseUrl } from "@/config/site";

/**
 * robots.txt — generated by Next.js at /robots.txt.
 * Allows crawling and points to the sitemap. The base URL comes from
 * NEXT_PUBLIC_SITE_URL in production (localhost fallback in development).
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = getBaseUrl();

  return {
    rules: {
      userAgent: "*",
      allow: "/",
    },
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
