import type { MetadataRoute } from "next";
import { getBaseUrl, siteConfig } from "@/config/site";

/**
 * sitemap.xml — generated by Next.js at /sitemap.xml from the built routes in
 * `siteConfig.routes`. The base URL comes from NEXT_PUBLIC_SITE_URL in
 * production (localhost fallback in development).
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = getBaseUrl();
  const lastModified = new Date();

  return siteConfig.routes.map((path) => ({
    url: `${baseUrl}${path === "/" ? "" : path}`,
    lastModified,
    changeFrequency: "monthly",
    priority: path === "/" ? 1 : 0.8,
  }));
}
